-- Dữ liệu tham chiếu cần có ở mọi môi trường (kể cả chạy thật): showroom Q4, thị trường, vai trò,
-- danh sách quyền và mặc định theo vai trò, danh mục mặc định (CLAUDE.md mục 5, 6, 7).
-- Dữ liệu giả cho dev nằm ở supabase/seed.sql.

insert into public.showrooms (id, code, name, timezone)
values ('4a000000-0000-4000-8000-000000000004', 'Q4', 'Showroom Quận 4', 'Asia/Ho_Chi_Minh');

insert into public.markets (showroom_id, country_code, name, timezone, call_windows, allowed_channels, color_token, sort)
values
  ('4a000000-0000-4000-8000-000000000004', 'VN', 'Việt Nam', 'Asia/Ho_Chi_Minh',
   '[{"days":[1,2,3,4,5,6],"start":"08:30","end":"20:30"},{"days":[7],"start":"09:00","end":"17:00"}]',
   array['call', 'zalo_oa', 'zns', 'sms'], 'loc-vn', 1),
  ('4a000000-0000-4000-8000-000000000004', 'KR', 'Hàn Quốc', 'Asia/Seoul',
   '[{"days":[1,2,3,4,5],"start":"19:00","end":"22:30"},{"days":[6,7],"start":"09:00","end":"22:30"}]',
   array['call', 'zalo_oa'], 'loc-kr', 2);

insert into public.roles (showroom_id, key, name, is_system, is_owner)
values
  ('4a000000-0000-4000-8000-000000000004', 'owner', 'Chủ hệ thống', true, true),
  ('4a000000-0000-4000-8000-000000000004', 'sale_admin', 'Sale admin', true, false),
  ('4a000000-0000-4000-8000-000000000004', 'telesale', 'Telesale', true, false);

-- Sinh tự động từ lib/auth/permissions.ts bằng scripts/gen-permission-seed.ts. Không sửa tay.
insert into public.permissions (key, "group", description, grantable, sensitive) values
  ('lead.view_own', 'Lead', 'Xem lead được giao cho mình', true, false),
  ('lead.view_all', 'Lead', 'Xem mọi lead của showroom', true, false),
  ('lead.create', 'Lead', 'Tạo lead', true, false),
  ('lead.edit_own', 'Lead', 'Sửa lead của mình', true, false),
  ('lead.edit_all', 'Lead', 'Sửa mọi lead', true, false),
  ('lead.assign', 'Lead', 'Giao, chuyển lead cho người khác', true, false),
  ('lead.import', 'Lead', 'Nhập lead từ file', true, false),
  ('lead.export', 'Lead', 'Xuất danh sách khách ra file', true, true),
  ('lead.delete', 'Lead', 'Xóa lead', true, true),
  ('lead.mark_lost', 'Lead', 'Đánh dấu lead thất bại', true, false),
  ('lead.receive', 'Lead', 'Được phân lead tự động khi đang trực', true, false),
  ('contact.phone_reveal', 'Khách', 'Xem đầy đủ số điện thoại của mọi khách', true, true),
  ('contact.phone_reveal_assigned', 'Khách', 'Xem số đầy đủ của khách thuộc lead đang giao cho mình', true, false),
  ('contact.merge', 'Khách', 'Gộp hai hồ sơ khách trùng', true, false),
  ('household.manage', 'Khách', 'Tạo hộ, gắn thành viên vào hộ', true, false),
  ('call.make', 'Cuộc gọi', 'Gọi từ CRM', true, false),
  ('call.recording_own', 'Cuộc gọi', 'Nghe ghi âm cuộc gọi của mình', true, false),
  ('call.recording_all', 'Cuộc gọi', 'Nghe ghi âm của mọi người', true, true),
  ('message.zalo_send', 'Tin nhắn', 'Gửi tin Zalo OA', true, false),
  ('message.view_all', 'Tin nhắn', 'Xem mọi hội thoại', true, false),
  ('catalog.view', 'Danh mục', 'Xem danh mục tra cứu', true, false),
  ('catalog.manage', 'Danh mục', 'Sửa danh mục tra cứu', true, false),
  ('product.view', 'Sản phẩm', 'Xem sản phẩm, giá bán, tồn khả dụng', true, false),
  ('product.manage', 'Sản phẩm', 'Thêm, sửa sản phẩm, SKU', true, false),
  ('product.view_cost', 'Sản phẩm', 'Xem giá vốn, biên lợi nhuận', true, true),
  ('price.manage', 'Sản phẩm', 'Sửa bảng giá', true, false),
  ('inventory.view', 'Tồn kho', 'Xem tồn kho, sổ kho', true, false),
  ('inventory.document', 'Tồn kho', 'Lập phiếu nhập, xuất, chuyển kho, kiểm kê', true, false),
  ('inventory.post', 'Tồn kho', 'Ghi sổ phiếu kho', true, false),
  ('inventory.count_approve', 'Tồn kho', 'Duyệt chênh lệch kiểm kê', true, false),
  ('combo.manage', 'Combo', 'Tạo, sửa combo', true, false),
  ('policy.view', 'Chính sách', 'Xem chính sách đang áp', true, false),
  ('policy.manage', 'Chính sách', 'Tạo, sửa, bật tắt chính sách', true, false),
  ('quote.create', 'Báo giá, đơn', 'Tạo, gửi báo giá', true, false),
  ('order.view_own', 'Báo giá, đơn', 'Xem đơn của mình', true, false),
  ('order.view_all', 'Báo giá, đơn', 'Xem mọi đơn', true, false),
  ('order.create', 'Báo giá, đơn', 'Tạo đơn', true, false),
  ('order.edit_own', 'Báo giá, đơn', 'Sửa đơn của mình', true, false),
  ('order.edit_all', 'Báo giá, đơn', 'Sửa mọi đơn', true, false),
  ('order.discount_approve', 'Báo giá, đơn', 'Duyệt đơn giảm giá vượt giới hạn', true, true),
  ('order.cancel', 'Báo giá, đơn', 'Hủy đơn', true, false),
  ('order.allow_backorder', 'Báo giá, đơn', 'Cho đặt trước khi chưa đủ hàng', true, false),
  ('order.export', 'Báo giá, đơn', 'Xuất danh sách đơn ra file', true, true),
  ('payment.record', 'Thanh toán', 'Ghi nhận khoản khách trả', true, false),
  ('payment.confirm', 'Thanh toán', 'Xác nhận tiền đã về', true, true),
  ('payment.refund', 'Thanh toán', 'Ghi hoàn tiền', true, true),
  ('staff.view', 'Đội ngũ', 'Xem hồ sơ làm việc của nhân sự', true, false),
  ('staff.manage', 'Đội ngũ', 'Sửa hồ sơ nhân sự, xếp ca, duyệt nghỉ', true, false),
  ('staff.offboard', 'Đội ngũ', 'Chạy trình bàn giao khi nghỉ việc', false, false),
  ('target.manage', 'Đội ngũ', 'Đặt chỉ tiêu', true, false),
  ('kpi.own', 'Đội ngũ', 'Xem chỉ số của mình', true, false),
  ('kpi.team', 'Đội ngũ', 'Xem chỉ số của từng người trong đội', true, false),
  ('kpi.leaderboard', 'Đội ngũ', 'Xem bảng xếp hạng có tên', true, false),
  ('attendance.view_team', 'Đội ngũ', 'Xem giờ trực, nghỉ của đội', true, false),
  ('coaching.manage', 'Đội ngũ', 'Viết, đọc ghi chú kèm cặp', true, false),
  ('delivery.update', 'Giao, bảo hành', 'Cập nhật bước giao lắp', true, false),
  ('warranty.manage', 'Giao, bảo hành', 'Tạo, sửa phiếu bảo hành', true, false),
  ('report.own', 'Báo cáo', 'Xem báo cáo của mình', true, false),
  ('report.team', 'Báo cáo', 'Xem báo cáo cả đội', true, false),
  ('settings.assignment', 'Cài đặt', 'Sửa luật phân lead, ca trực, thị trường', true, false),
  ('settings.integrations', 'Cài đặt', 'Kết nối Meta, Zalo, tổng đài', true, false),
  ('settings.users', 'Cài đặt', 'Mời, khóa người dùng', false, false),
  ('settings.permissions', 'Cài đặt', 'Bật tắt quyền', false, false),
  ('audit.view', 'Kiểm toán', 'Xem nhật ký kiểm toán', true, false)
on conflict (key) do update set "group" = excluded."group", description = excluded.description,
  grantable = excluded.grantable, sensitive = excluded.sensitive;

insert into public.role_permissions (role_id, permission_key)
select r.id, v.permission_key from (values
  ('owner', 'lead.view_own'),
  ('sale_admin', 'lead.view_own'),
  ('telesale', 'lead.view_own'),
  ('owner', 'lead.view_all'),
  ('sale_admin', 'lead.view_all'),
  ('owner', 'lead.create'),
  ('sale_admin', 'lead.create'),
  ('telesale', 'lead.create'),
  ('owner', 'lead.edit_own'),
  ('sale_admin', 'lead.edit_own'),
  ('telesale', 'lead.edit_own'),
  ('owner', 'lead.edit_all'),
  ('sale_admin', 'lead.edit_all'),
  ('owner', 'lead.assign'),
  ('sale_admin', 'lead.assign'),
  ('owner', 'lead.import'),
  ('sale_admin', 'lead.import'),
  ('owner', 'lead.export'),
  ('owner', 'lead.delete'),
  ('owner', 'lead.mark_lost'),
  ('sale_admin', 'lead.mark_lost'),
  ('telesale', 'lead.mark_lost'),
  ('telesale', 'lead.receive'),
  ('owner', 'contact.phone_reveal'),
  ('sale_admin', 'contact.phone_reveal'),
  ('owner', 'contact.phone_reveal_assigned'),
  ('sale_admin', 'contact.phone_reveal_assigned'),
  ('telesale', 'contact.phone_reveal_assigned'),
  ('owner', 'contact.merge'),
  ('sale_admin', 'contact.merge'),
  ('owner', 'household.manage'),
  ('sale_admin', 'household.manage'),
  ('telesale', 'household.manage'),
  ('owner', 'call.make'),
  ('sale_admin', 'call.make'),
  ('telesale', 'call.make'),
  ('owner', 'call.recording_own'),
  ('sale_admin', 'call.recording_own'),
  ('telesale', 'call.recording_own'),
  ('owner', 'call.recording_all'),
  ('sale_admin', 'call.recording_all'),
  ('owner', 'message.zalo_send'),
  ('sale_admin', 'message.zalo_send'),
  ('telesale', 'message.zalo_send'),
  ('owner', 'message.view_all'),
  ('sale_admin', 'message.view_all'),
  ('owner', 'catalog.view'),
  ('sale_admin', 'catalog.view'),
  ('telesale', 'catalog.view'),
  ('owner', 'catalog.manage'),
  ('sale_admin', 'catalog.manage'),
  ('owner', 'product.view'),
  ('sale_admin', 'product.view'),
  ('telesale', 'product.view'),
  ('owner', 'product.manage'),
  ('sale_admin', 'product.manage'),
  ('owner', 'product.view_cost'),
  ('owner', 'price.manage'),
  ('owner', 'inventory.view'),
  ('sale_admin', 'inventory.view'),
  ('telesale', 'inventory.view'),
  ('owner', 'inventory.document'),
  ('sale_admin', 'inventory.document'),
  ('owner', 'inventory.post'),
  ('sale_admin', 'inventory.post'),
  ('owner', 'inventory.count_approve'),
  ('owner', 'combo.manage'),
  ('owner', 'policy.view'),
  ('sale_admin', 'policy.view'),
  ('telesale', 'policy.view'),
  ('owner', 'policy.manage'),
  ('owner', 'quote.create'),
  ('sale_admin', 'quote.create'),
  ('telesale', 'quote.create'),
  ('owner', 'order.view_own'),
  ('sale_admin', 'order.view_own'),
  ('telesale', 'order.view_own'),
  ('owner', 'order.view_all'),
  ('sale_admin', 'order.view_all'),
  ('owner', 'order.create'),
  ('sale_admin', 'order.create'),
  ('telesale', 'order.create'),
  ('owner', 'order.edit_own'),
  ('sale_admin', 'order.edit_own'),
  ('telesale', 'order.edit_own'),
  ('owner', 'order.edit_all'),
  ('sale_admin', 'order.edit_all'),
  ('owner', 'order.discount_approve'),
  ('owner', 'order.cancel'),
  ('sale_admin', 'order.cancel'),
  ('owner', 'order.allow_backorder'),
  ('sale_admin', 'order.allow_backorder'),
  ('owner', 'order.export'),
  ('owner', 'payment.record'),
  ('sale_admin', 'payment.record'),
  ('telesale', 'payment.record'),
  ('owner', 'payment.confirm'),
  ('sale_admin', 'payment.confirm'),
  ('owner', 'payment.refund'),
  ('owner', 'staff.view'),
  ('sale_admin', 'staff.view'),
  ('owner', 'staff.manage'),
  ('owner', 'staff.offboard'),
  ('owner', 'target.manage'),
  ('owner', 'kpi.own'),
  ('sale_admin', 'kpi.own'),
  ('telesale', 'kpi.own'),
  ('owner', 'kpi.team'),
  ('sale_admin', 'kpi.team'),
  ('owner', 'kpi.leaderboard'),
  ('sale_admin', 'kpi.leaderboard'),
  ('owner', 'attendance.view_team'),
  ('sale_admin', 'attendance.view_team'),
  ('owner', 'coaching.manage'),
  ('sale_admin', 'coaching.manage'),
  ('owner', 'delivery.update'),
  ('sale_admin', 'delivery.update'),
  ('owner', 'warranty.manage'),
  ('sale_admin', 'warranty.manage'),
  ('owner', 'report.own'),
  ('sale_admin', 'report.own'),
  ('telesale', 'report.own'),
  ('owner', 'report.team'),
  ('sale_admin', 'report.team'),
  ('owner', 'settings.assignment'),
  ('sale_admin', 'settings.assignment'),
  ('owner', 'settings.integrations'),
  ('owner', 'settings.users'),
  ('owner', 'settings.permissions'),
  ('owner', 'audit.view')
) as v (role_key, permission_key)
join public.roles r on r.key = v.role_key
on conflict do nothing;

-- Danh mục mặc định (mục 6). Đội dùng thử 2 tuần rồi chỉnh trong Cài đặt.
insert into public.lead_sources (showroom_id, key, label, sort)
select '4a000000-0000-4000-8000-000000000004', v.key, v.label, v.sort from (values
  ('fb_ads_kr', 'Facebook Ads nhắm người Việt tại Hàn', 1),
  ('fb_ads_vn', 'Facebook Ads trong nước', 2),
  ('fb_messenger', 'Tin nhắn Facebook', 3),
  ('zalo_oa', 'Zalo OA', 4),
  ('tiktok_live', 'Live TikTok', 5),
  ('koc_kol', 'KOC, KOL', 6),
  ('tiktok_shop', 'TikTok Shop', 7),
  ('walk_in', 'Khách đến showroom', 8),
  ('hotline', 'Hotline', 9),
  ('referral', 'Giới thiệu từ khách cũ', 10),
  ('import', 'Dữ liệu cũ nhập lại', 11)
) as v (key, label, sort);

insert into public.occasions (showroom_id, key, label, sort)
select '4a000000-0000-4000-8000-000000000004', v.key, v.label, v.sort from (values
  ('tet', 'Tết', 1),
  ('vn_women_day', '20/10', 2),
  ('intl_women_day', '8/3', 3),
  ('birthday', 'Sinh nhật', 4),
  ('longevity', 'Mừng thọ', 5),
  ('vu_lan', 'Vu Lan', 6),
  ('housewarming', 'Tân gia', 7),
  ('family_use', 'Không có dịp, dùng cho gia đình', 8)
) as v (key, label, sort);

insert into public.call_outcomes (showroom_id, key, label, sort)
select '4a000000-0000-4000-8000-000000000004', v.key, v.label, v.sort from (values
  ('answered_interested', 'Nghe máy, quan tâm', 1),
  ('answered_not_interested', 'Nghe máy, chưa quan tâm', 2),
  ('callback', 'Hẹn gọi lại', 3),
  ('no_answer', 'Không nghe máy', 4),
  ('wrong_number', 'Thuê bao, sai số', 5),
  ('zalo_interested', 'Đã gọi qua Zalo, quan tâm', 6),
  ('zalo_no_reply', 'Đã gọi qua Zalo, không trả lời', 7)
) as v (key, label, sort);

insert into public.lost_reasons (showroom_id, key, label, sort)
select '4a000000-0000-4000-8000-000000000004', v.key, v.label, v.sort from (values
  ('price_high', 'Giá cao', 1),
  ('bought_elsewhere', 'Đã mua nơi khác', 2),
  ('distrust_remote', 'Chưa tin mua từ xa', 3),
  ('recipient_declined', 'Người nhận không muốn nhận', 4),
  ('no_delivery_area', 'Không giao được tới khu vực', 5),
  ('price_check_only', 'Hết nhu cầu, chỉ hỏi giá', 6),
  ('unreachable_5', 'Không liên lạc được sau 5 lần', 7),
  ('fake_number', 'Sai số, số ảo', 8),
  ('duplicate', 'Trùng lead', 9)
) as v (key, label, sort);

insert into public.budget_ranges (showroom_id, key, label, sort)
select '4a000000-0000-4000-8000-000000000004', v.key, v.label, v.sort from (values
  ('lt_30m', 'Dưới 30tr', 1),
  ('30_50m', '30–50tr', 2),
  ('50_80m', '50–80tr', 3),
  ('gt_80m', 'Trên 80tr', 4),
  ('unknown', 'Chưa rõ', 5)
) as v (key, label, sort);
