import type { AttributedLead, KocData } from "./types";

// Dữ liệu giả cho màn KOL, KOC (bản demo). Tên, kênh, số điện thoại đều là giả. Ngày theo đồng hồ mô phỏng của
// bản demo (hôm nay 04/10/2026 giờ VN). Mã nhân sự trùng supabase/seed.sql: Owner …0001, sale admin …0002.

export const KOC_TODAY = "2026-10-04";

const OWNER = "11111111-1111-4111-8111-000000000001";
const ADMIN = "11111111-1111-4111-8111-000000000002";

const PRICE = { X9: 79_900_000, S7: 49_900_000, M5: 32_900_000, I3: 18_900_000, F2: 6_900_000 };

type L = [string, string | null, string, AttributedLead["market"], string, AttributedLead["stage"], number];
const leads = (creatorId: string, rows: L[]): AttributedLead[] =>
  rows.map(([id, bookingId, name, market, createdAt, stage, orderValue]) => ({
    id,
    creatorId,
    bookingId,
    name,
    market,
    createdAt,
    stage,
    orderValue,
  }));

export function kocSeed(): KocData {
  return {
    creators: [
      {
        id: "koc-ansan",
        name: "Vợ chồng Ansan",
        realName: "Nguyễn Văn Khải, Trần Thị Mỹ",
        kind: "koc",
        status: "active",
        ownerId: ADMIN,
        audience: "KR",
        livesIn: "Ansan, Hàn Quốc",
        niches: ["Đời sống người Việt ở Hàn", "Quà cho bố mẹ"],
        channels: [
          {
            platform: "tiktok",
            handle: "@vochongansan",
            url: "https://www.tiktok.com/@vochongansan",
            followers: 48_200,
            avgViews: 61_000,
            engagementRate: 6.1,
            updatedAt: "2026-10-01",
          },
          {
            platform: "facebook",
            handle: "Vợ Chồng Ansan",
            url: "https://www.facebook.com/vochongansan",
            followers: 22_000,
            avgViews: 9_500,
            engagementRate: 3.4,
            updatedAt: "2026-10-01",
          },
        ],
        rates: [
          { format: "short_video", price: 6_000_000 },
          { format: "livestream", price: 9_000_000 },
          { format: "story", price: 1_500_000 },
        ],
        contract: {
          code: "HĐ-KOC-2609-01",
          startsOn: "2026-09-01",
          endsOn: "2027-02-28",
          commissionRate: 3,
          exclusivity: null,
          usageRightsMonths: 6,
          status: "signed",
          files: [
            {
              id: "cf-01",
              name: "hop-dong-vo-chong-ansan.pdf",
              kind: "contract",
              size: 517000,
              mime: "application/pdf",
              uploadedAt: "2026-09-01",
              uploadedBy: ADMIN,
              url: null,
            },
          ],
        },
        trackingCode: "ANSAN",
        phoneMasked: "+82 10••••7731",
        phoneFull: "+821055517731",
        zalo: true,
        agency: null,
        tags: ["Đúng hạn", "Khán giả 30–45 tuổi"],
        note: "Hai vợ chồng làm ở nhà máy Ansan, khán giả là người Việt đi làm ở Hàn. Hay quay cảnh gọi video về quê.",
        rating: {
          content: 5,
          punctuality: 5,
          results: 4,
          note: "Video Tết kéo 9 lead trong 2 tuần, khách hỏi rất đúng nhu cầu mua cho bố mẹ.",
          by: ADMIN,
          at: "2026-09-30",
        },
        createdAt: "2026-08-20",
      },
      {
        id: "koc-hanh",
        name: "Chị Hạnh Daegu",
        realName: "Lê Thị Hạnh",
        kind: "koc",
        status: "active",
        ownerId: ADMIN,
        audience: "KR",
        livesIn: "Daegu, Hàn Quốc",
        niches: ["Mẹ bỉm ở Hàn", "Sức khỏe gia đình"],
        channels: [
          {
            platform: "tiktok",
            handle: "@chihanhdaegu",
            url: "https://www.tiktok.com/@chihanhdaegu",
            followers: 31_400,
            avgViews: 27_000,
            engagementRate: 5.2,
            updatedAt: "2026-09-29",
          },
          {
            platform: "facebook",
            handle: "Hạnh Daegu",
            url: "https://www.facebook.com/hanhdaegu",
            followers: 15_300,
            avgViews: 6_200,
            engagementRate: 4.1,
            updatedAt: "2026-09-29",
          },
        ],
        rates: [
          { format: "short_video", price: 5_000_000 },
          { format: "post", price: 3_500_000 },
        ],
        contract: {
          code: "HĐ-KOC-2609-02",
          startsOn: "2026-09-05",
          endsOn: "2026-12-31",
          commissionRate: 3,
          exclusivity: null,
          usageRightsMonths: 3,
          status: "signed",
          files: [
            {
              id: "cf-02",
              name: "hop-dong-chi-hanh.pdf",
              kind: "contract",
              size: 554000,
              mime: "application/pdf",
              uploadedAt: "2026-09-01",
              uploadedBy: ADMIN,
              url: null,
            },
          ],
        },
        trackingCode: "HANHDG",
        phoneMasked: "+82 10••••2408",
        phoneFull: "+821077712408",
        zalo: true,
        agency: null,
        tags: ["Nói chuyện tự nhiên"],
        note: "Hợp nhóm khách mua máy massage chân, máy lọc nước tặng mẹ.",
        rating: null,
        createdAt: "2026-09-01",
      },
      {
        id: "kol-seoul",
        name: "Ẩm thực Việt ở Seoul",
        realName: "Phạm Quang Huy",
        kind: "kol",
        status: "negotiating",
        ownerId: OWNER,
        audience: "KR",
        livesIn: "Seoul, Hàn Quốc",
        niches: ["Ẩm thực", "Đời sống du học sinh"],
        channels: [
          {
            platform: "youtube",
            handle: "@amthucvietseoul",
            url: "https://www.youtube.com/@amthucvietseoul",
            followers: 210_000,
            avgViews: 85_000,
            engagementRate: 3.1,
            updatedAt: "2026-09-28",
          },
          {
            platform: "tiktok",
            handle: "@amthucvietseoul",
            url: "https://www.tiktok.com/@amthucvietseoul",
            followers: 180_000,
            avgViews: 120_000,
            engagementRate: 4.4,
            updatedAt: "2026-09-28",
          },
          {
            platform: "instagram",
            handle: "@amthucvietseoul",
            url: "https://www.instagram.com/amthucvietseoul",
            followers: 40_000,
            avgViews: 8_000,
            engagementRate: 2.2,
            updatedAt: "2026-09-28",
          },
        ],
        rates: [
          { format: "short_video", price: 25_000_000 },
          { format: "livestream", price: 35_000_000 },
        ],
        contract: null,
        trackingCode: "SEOULFOOD",
        phoneMasked: "+82 10••••5590",
        phoneFull: "+821044455590",
        zalo: false,
        agency: "Công ty truyền thông Hàn Việt Media",
        tags: ["Khán giả trẻ"],
        note: "Khán giả trẻ, ít người mua ghế cho bản thân; thử một video quà tặng bố mẹ trước khi ký dài hạn.",
        rating: null,
        createdAt: "2026-09-25",
      },
      {
        id: "kol-mehien",
        name: "Mẹ Hiền Review",
        realName: "Đỗ Thu Hiền",
        kind: "kol",
        status: "active",
        ownerId: OWNER,
        audience: "VN",
        livesIn: "TP.HCM",
        niches: ["Đồ gia dụng", "Sức khỏe gia đình"],
        channels: [
          {
            platform: "tiktok",
            handle: "@mehienreview",
            url: "https://www.tiktok.com/@mehienreview",
            followers: 520_000,
            avgViews: 310_000,
            engagementRate: 3.8,
            updatedAt: "2026-10-02",
          },
          {
            platform: "facebook",
            handle: "Mẹ Hiền Review",
            url: "https://www.facebook.com/mehienreview",
            followers: 300_000,
            avgViews: 45_000,
            engagementRate: 1.9,
            updatedAt: "2026-10-02",
          },
        ],
        rates: [
          { format: "short_video", price: 30_000_000 },
          { format: "livestream", price: 45_000_000 },
          { format: "post", price: 12_000_000 },
        ],
        contract: {
          code: "HĐ-KOL-2608-01",
          startsOn: "2026-08-15",
          endsOn: "2027-02-15",
          commissionRate: 2,
          exclusivity: "Không nhận quảng cáo ghế massage, máy lọc nước hãng khác trong thời hạn hợp đồng",
          usageRightsMonths: 12,
          status: "signed",
          files: [
            {
              id: "cf-03",
              name: "hop-dong-me-hien.pdf",
              kind: "contract",
              size: 591000,
              mime: "application/pdf",
              uploadedAt: "2026-09-01",
              uploadedBy: ADMIN,
              url: null,
            },
          ],
        },
        trackingCode: "MEHIEN",
        phoneMasked: "090•••318",
        phoneFull: "+84909111318",
        zalo: true,
        agency: "Hiền Media (quản lý: chị Vy)",
        tags: ["Độc quyền ngành hàng", "Livestream bán tốt"],
        note: "Kênh lớn nhất đang hợp tác. Khách từ kênh này chủ yếu ở TP.HCM và miền Tây.",
        rating: {
          content: 4,
          punctuality: 4,
          results: 4,
          note: "Lượt xem cao, lead nhiều nhưng tỷ lệ chốt thấp hơn KOC ở Hàn.",
          by: OWNER,
          at: "2026-09-28",
        },
        createdAt: "2026-08-10",
      },
      {
        id: "koc-baotram",
        name: "Bảo Trâm sống khỏe",
        realName: "Võ Bảo Trâm",
        kind: "koc",
        status: "active",
        ownerId: ADMIN,
        audience: "VN",
        livesIn: "Quận 7, TP.HCM",
        niches: ["Sống khỏe", "Yoga"],
        channels: [
          {
            platform: "tiktok",
            handle: "@baotramsongkhoe",
            url: "https://www.tiktok.com/@baotramsongkhoe",
            followers: 18_300,
            avgViews: 22_000,
            engagementRate: 7.2,
            updatedAt: "2026-09-30",
          },
        ],
        rates: [
          { format: "short_video", price: 3_000_000 },
          { format: "showroom_visit", price: 4_000_000 },
        ],
        contract: {
          code: "HĐ-KOC-2609-03",
          startsOn: "2026-09-20",
          endsOn: "2027-03-20",
          commissionRate: 5,
          exclusivity: null,
          usageRightsMonths: 6,
          status: "signed",
          files: [],
        },
        trackingCode: "BAOTRAM",
        phoneMasked: "093•••772",
        phoneFull: "+84938222772",
        zalo: true,
        agency: null,
        tags: ["Tương tác cao", "Ở gần showroom"],
        note: "Ở Quận 7, quay tại showroom được; khách đến xem trực tiếp nhiều.",
        rating: null,
        createdAt: "2026-09-15",
      },
      {
        id: "aff-tuan",
        name: "Tuấn Busan",
        realName: "Hoàng Minh Tuấn",
        kind: "affiliate",
        status: "active",
        ownerId: ADMIN,
        audience: "KR",
        livesIn: "Busan, Hàn Quốc",
        niches: ["Hội đồng hương ở Busan"],
        channels: [
          {
            platform: "facebook",
            handle: "Tuấn Busan",
            url: "https://www.facebook.com/tuanbusan",
            followers: 6_500,
            avgViews: 2_100,
            engagementRate: 5.5,
            updatedAt: "2026-09-20",
          },
        ],
        rates: [],
        contract: {
          code: "HĐ-AFF-2609-01",
          startsOn: "2026-09-10",
          endsOn: "2027-09-10",
          commissionRate: 5,
          exclusivity: null,
          usageRightsMonths: 0,
          status: "signed",
          files: [],
        },
        trackingCode: "TUANBS",
        phoneMasked: "+82 10••••0612",
        phoneFull: "+821033300612",
        zalo: true,
        agency: null,
        tags: ["Chỉ ăn hoa hồng"],
        note: "Khách cũ, giới thiệu trong hội đồng hương; không nhận phí cố định, chỉ hoa hồng trên đơn hoàn tất.",
        rating: null,
        createdAt: "2026-09-10",
      },
      {
        id: "koc-ngoc",
        name: "Ngọc Gia Đình Nhỏ",
        realName: "Trương Bích Ngọc",
        kind: "koc",
        status: "prospect",
        ownerId: ADMIN,
        audience: "VN",
        livesIn: "Cần Thơ",
        niches: ["Gia đình trẻ", "Mẹ và bé"],
        channels: [
          {
            platform: "tiktok",
            handle: "@ngocgiadinhnho",
            url: "https://www.tiktok.com/@ngocgiadinhnho",
            followers: 12_100,
            avgViews: 9_800,
            engagementRate: 6.4,
            updatedAt: "2026-09-26",
          },
          {
            platform: "instagram",
            handle: "@ngocgiadinhnho",
            url: "https://www.instagram.com/ngocgiadinhnho",
            followers: 9_000,
            avgViews: 1_800,
            engagementRate: 3.0,
            updatedAt: "2026-09-26",
          },
        ],
        rates: [{ format: "short_video", price: 2_500_000 }],
        contract: null,
        trackingCode: "NGOCGD",
        phoneMasked: "091•••045",
        phoneFull: "+84911555045",
        zalo: true,
        agency: null,
        tags: ["Miền Tây"],
        note: "Đang gửi báo giá, chờ chị Ngọc xem lịch tháng 11.",
        rating: null,
        createdAt: "2026-09-26",
      },
      {
        id: "koc-lam",
        name: "Lâm Đi Làm Ở Hàn",
        realName: "Đinh Văn Lâm",
        kind: "koc",
        status: "paused",
        ownerId: ADMIN,
        audience: "KR",
        livesIn: "Gimhae, Hàn Quốc",
        niches: ["Lao động Việt ở Hàn"],
        channels: [
          {
            platform: "tiktok",
            handle: "@lamdilamohan",
            url: "https://www.tiktok.com/@lamdilamohan",
            followers: 27_000,
            avgViews: 14_000,
            engagementRate: 4.0,
            updatedAt: "2026-09-15",
          },
        ],
        rates: [{ format: "short_video", price: 4_000_000 }],
        contract: {
          code: "HĐ-KOC-2608-04",
          startsOn: "2026-08-01",
          endsOn: "2026-09-30",
          commissionRate: 3,
          exclusivity: null,
          usageRightsMonths: 3,
          status: "expired",
          files: [
            {
              id: "cf-04",
              name: "hop-dong-lam.pdf",
              kind: "contract",
              size: 628000,
              mime: "application/pdf",
              uploadedAt: "2026-09-01",
              uploadedBy: ADMIN,
              url: null,
            },
          ],
        },
        trackingCode: "LAMHAN",
        phoneMasked: "+82 10••••9920",
        phoneFull: "+821066619920",
        zalo: false,
        agency: null,
        tags: ["Đăng trễ"],
        note: "Tạm dừng: hai lần đăng trễ so với lịch, một booking phải hủy.",
        rating: {
          content: 3,
          punctuality: 1,
          results: 2,
          note: "Đăng trễ 3 ngày ở booking Trung thu, lỡ dịp.",
          by: ADMIN,
          at: "2026-09-18",
        },
        createdAt: "2026-07-28",
      },
    ],
    bookings: [
      {
        id: "bk-01",
        creatorId: "koc-ansan",
        campaign: "Quà Tết sớm cho bố mẹ ở quê",
        products: ["Ghế massage DV-X9"],
        format: "short_video",
        postAt: "2026-09-19T12:00:00Z",
        fee: 6_000_000,
        commissionRate: 3,
        status: "paid",
        createdBy: ADMIN,
        approvedBy: null,
        posts: [
          {
            url: "https://www.tiktok.com/@vochongansan/video/7420001",
            platform: "tiktok",
            postedAt: "2026-09-19T12:05:00Z",
            views: 182_000,
            likes: 9_400,
            comments: 610,
            shares: 380,
          },
        ],
        note: "Quay cảnh gọi video cho bố, bố ngồi thử ghế ở showroom.",
        cancelReason: null,
      },
      {
        id: "bk-02",
        creatorId: "koc-ansan",
        campaign: "Mừng thọ, quà 20/10",
        products: ["Ghế massage DV-S7"],
        format: "livestream",
        postAt: "2026-10-10T11:00:00Z",
        fee: 9_000_000,
        commissionRate: 3,
        status: "script_approved",
        createdBy: ADMIN,
        approvedBy: null,
        posts: [],
        note: "Live 20:00 giờ Hàn thứ Bảy, có telesale trực ca tối để chốt.",
        cancelReason: null,
      },
      {
        id: "bk-03",
        creatorId: "koc-hanh",
        campaign: "Quà 20/10 cho mẹ",
        products: ["Máy massage chân DV-F2"],
        format: "short_video",
        postAt: "2026-10-05T10:00:00Z",
        fee: 5_000_000,
        commissionRate: 3,
        status: "sample_sent",
        createdBy: ADMIN,
        approvedBy: null,
        posts: [],
        note: "",
        cancelReason: null,
      },
      {
        id: "bk-04",
        creatorId: "kol-seoul",
        campaign: "Ra mắt DV-X9 cho người Việt tại Hàn",
        products: ["Ghế massage DV-X9"],
        format: "short_video",
        postAt: "2026-10-18T10:00:00Z",
        fee: 25_000_000,
        commissionRate: 0,
        status: "budget_pending",
        createdBy: ADMIN,
        approvedBy: null,
        posts: [],
        note: "Thử một video trước khi ký dài hạn.",
        cancelReason: null,
      },
      {
        id: "bk-05",
        creatorId: "kol-mehien",
        campaign: "Review máy lọc nước ion kiềm",
        products: ["Máy lọc nước ion kiềm DV-I3"],
        format: "short_video",
        postAt: "2026-09-12T12:00:00Z",
        fee: 30_000_000,
        commissionRate: 2,
        status: "accepted",
        createdBy: OWNER,
        approvedBy: OWNER,
        posts: [
          {
            url: "https://www.tiktok.com/@mehienreview/video/7410042",
            platform: "tiktok",
            postedAt: "2026-09-12T12:00:00Z",
            views: 640_000,
            likes: 21_000,
            comments: 1_350,
            shares: 2_100,
          },
        ],
        note: "Thanh toán 2 đợt: 50% khi chốt, 50% sau nghiệm thu.",
        cancelReason: null,
      },
      {
        id: "bk-06",
        creatorId: "kol-mehien",
        campaign: "Live Tết sớm, combo ghế và gối cổ",
        products: ["Ghế massage DV-X9", "Gối massage cổ"],
        format: "livestream",
        postAt: "2026-10-12T13:00:00Z",
        fee: 45_000_000,
        commissionRate: 2,
        status: "confirmed",
        createdBy: OWNER,
        approvedBy: OWNER,
        posts: [],
        note: "Cần 2 telesale trực trong giờ live.",
        cancelReason: null,
      },
      {
        id: "bk-07",
        creatorId: "koc-baotram",
        campaign: "Trải nghiệm tại showroom Q4",
        products: ["Ghế massage DV-M5"],
        format: "showroom_visit",
        postAt: "2026-09-27T09:00:00Z",
        fee: 4_000_000,
        commissionRate: 5,
        status: "paid",
        createdBy: ADMIN,
        approvedBy: null,
        posts: [
          {
            url: "https://www.tiktok.com/@baotramsongkhoe/video/7425511",
            platform: "tiktok",
            postedAt: "2026-09-27T11:30:00Z",
            views: 52_000,
            likes: 4_100,
            comments: 290,
            shares: 160,
          },
        ],
        note: "",
        cancelReason: null,
      },
      {
        id: "bk-08",
        creatorId: "koc-baotram",
        campaign: "Nhắc thay lõi lọc định kỳ",
        products: ["Bộ lõi lọc thay thế"],
        format: "short_video",
        postAt: "2026-10-08T11:00:00Z",
        fee: 3_000_000,
        commissionRate: 5,
        status: "proposed",
        createdBy: ADMIN,
        approvedBy: null,
        posts: [],
        note: "",
        cancelReason: null,
      },
      {
        id: "bk-09",
        creatorId: "koc-hanh",
        campaign: "Giới thiệu showroom Q4 cho người ở Hàn",
        products: [],
        format: "post",
        postAt: "2026-09-14T11:00:00Z",
        fee: 3_500_000,
        commissionRate: 3,
        status: "paid",
        createdBy: ADMIN,
        approvedBy: null,
        posts: [
          {
            url: "https://www.facebook.com/hanhdaegu/posts/1029",
            platform: "facebook",
            postedAt: "2026-09-14T11:10:00Z",
            views: 41_000,
            likes: 1_900,
            comments: 240,
            shares: 95,
          },
        ],
        note: "",
        cancelReason: null,
      },
      {
        id: "bk-10",
        creatorId: "koc-lam",
        campaign: "Quà Trung thu gửi về quê",
        products: ["Máy massage chân DV-F2"],
        format: "short_video",
        postAt: "2026-09-08T12:00:00Z",
        fee: 4_000_000,
        commissionRate: 3,
        status: "paid",
        createdBy: ADMIN,
        approvedBy: null,
        posts: [
          {
            url: "https://www.tiktok.com/@lamdilamohan/video/7401177",
            platform: "tiktok",
            postedAt: "2026-09-11T13:00:00Z",
            views: 16_500,
            likes: 700,
            comments: 48,
            shares: 21,
          },
        ],
        note: "Đăng trễ 3 ngày so với lịch.",
        cancelReason: null,
      },
      {
        id: "bk-11",
        creatorId: "koc-lam",
        campaign: "Mừng thọ 20/10",
        products: ["Ghế massage DV-S7"],
        format: "short_video",
        postAt: "2026-09-26T12:00:00Z",
        fee: 4_000_000,
        commissionRate: 3,
        status: "cancelled",
        createdBy: ADMIN,
        approvedBy: null,
        posts: [],
        note: "",
        cancelReason: "Quá ngày hẹn chưa gửi kịch bản, tạm dừng hợp tác.",
      },
    ],
    samples: [
      {
        id: "sm-01",
        creatorId: "koc-ansan",
        bookingId: "bk-01",
        product: "Ghế massage DV-X9",
        serial: "X9-2609-0003",
        sentAt: "2026-09-12",
        status: "gifted",
      },
      {
        id: "sm-02",
        creatorId: "koc-ansan",
        bookingId: "bk-02",
        product: "Ghế massage DV-S7",
        serial: "S7-2609-0012",
        sentAt: "2026-09-30",
        status: "with_creator",
      },
      {
        id: "sm-03",
        creatorId: "koc-hanh",
        bookingId: "bk-03",
        product: "Máy massage chân DV-F2",
        serial: null,
        sentAt: "2026-09-29",
        status: "with_creator",
      },
      {
        id: "sm-04",
        creatorId: "kol-mehien",
        bookingId: "bk-05",
        product: "Máy lọc nước ion kiềm DV-I3",
        serial: "I3-2609-0007",
        sentAt: "2026-09-05",
        status: "returned",
      },
      {
        id: "sm-05",
        creatorId: "koc-lam",
        bookingId: "bk-10",
        product: "Máy massage chân DV-F2",
        serial: null,
        sentAt: "2026-09-01",
        status: "with_creator",
      },
    ],
    leads: [
      ...leads("koc-ansan", [
        ["kl-01", "bk-01", "Chị Hồng", "KR", "2026-09-19", "won", PRICE.X9],
        ["kl-02", "bk-01", "Anh Dũng", "KR", "2026-09-19", "won", PRICE.X9],
        ["kl-03", "bk-01", "Chị Thảo", "KR", "2026-09-20", "deposit", PRICE.S7],
        ["kl-04", "bk-01", "Anh Phát", "KR", "2026-09-20", "quoted", 0],
        ["kl-05", "bk-01", "Chị Liên", "KR", "2026-09-21", "contacted", 0],
        ["kl-06", "bk-01", "Anh Bình", "KR", "2026-09-21", "lost", 0],
        ["kl-07", "bk-01", "Chị Mai", "KR", "2026-09-23", "won", PRICE.S7],
        ["kl-08", null, "Anh Toàn", "KR", "2026-09-30", "new", 0],
        ["kl-09", null, "Chị Yến", "KR", "2026-10-02", "contacted", 0],
      ]),
      ...leads("koc-hanh", [
        ["kl-10", "bk-09", "Chị Ngân", "KR", "2026-09-14", "won", PRICE.F2],
        ["kl-11", "bk-09", "Chị Trang", "KR", "2026-09-15", "won", PRICE.I3],
        ["kl-12", "bk-09", "Anh Quang", "KR", "2026-09-16", "lost", 0],
        ["kl-13", null, "Chị Vân", "KR", "2026-09-28", "quoted", 0],
      ]),
      ...leads("kol-mehien", [
        ["kl-14", "bk-05", "Chị Lan", "VN", "2026-09-12", "won", PRICE.I3],
        ["kl-15", "bk-05", "Anh Sơn", "VN", "2026-09-12", "lost", 0],
        ["kl-16", "bk-05", "Chị Diệu", "VN", "2026-09-13", "won", PRICE.I3],
        ["kl-17", "bk-05", "Cô Bảy", "VN", "2026-09-13", "lost", 0],
        ["kl-18", "bk-05", "Anh Khang", "VN", "2026-09-13", "contacted", 0],
        ["kl-19", "bk-05", "Chị Huệ", "VN", "2026-09-14", "lost", 0],
        ["kl-20", "bk-05", "Chú Tư", "VN", "2026-09-14", "deposit", PRICE.I3],
        ["kl-21", "bk-05", "Chị Phương", "VN", "2026-09-15", "lost", 0],
        ["kl-22", "bk-05", "Anh Hải", "VN", "2026-09-16", "quoted", 0],
        ["kl-23", "bk-05", "Chị Thu", "VN", "2026-09-18", "won", PRICE.X9],
        ["kl-24", "bk-05", "Anh Nghĩa", "VN", "2026-09-20", "new", 0],
      ]),
      ...leads("koc-baotram", [
        ["kl-25", "bk-07", "Chị Hoa", "VN", "2026-09-27", "won", PRICE.M5],
        ["kl-26", "bk-07", "Anh Đức", "VN", "2026-09-28", "deposit", PRICE.M5],
        ["kl-27", "bk-07", "Chị Kim", "VN", "2026-09-29", "contacted", 0],
      ]),
      ...leads("aff-tuan", [
        ["kl-28", null, "Anh Hưng", "KR", "2026-09-18", "won", PRICE.S7],
        ["kl-29", null, "Chị Oanh", "KR", "2026-09-26", "quoted", 0],
      ]),
      ...leads("koc-lam", [["kl-30", "bk-10", "Anh Tài", "KR", "2026-09-12", "lost", 0]]),
    ],
    payouts: [
      {
        id: "po-01",
        creatorId: "koc-ansan",
        bookingId: "bk-01",
        kind: "fee",
        amount: 6_000_000,
        paidAt: "2026-09-24",
        reference: "CK 240926 ANSAN",
        recordedBy: ADMIN,
      },
      {
        id: "po-02",
        creatorId: "kol-mehien",
        bookingId: "bk-05",
        kind: "fee",
        amount: 15_000_000,
        paidAt: "2026-09-08",
        reference: "CK đợt 1 MEHIEN",
        recordedBy: OWNER,
      },
      {
        id: "po-03",
        creatorId: "koc-baotram",
        bookingId: "bk-07",
        kind: "fee",
        amount: 4_000_000,
        paidAt: "2026-09-30",
        reference: "CK 300926 BAOTRAM",
        recordedBy: ADMIN,
      },
      {
        id: "po-04",
        creatorId: "koc-hanh",
        bookingId: "bk-09",
        kind: "fee",
        amount: 3_500_000,
        paidAt: "2026-09-18",
        reference: "CK 180926 HANHDG",
        recordedBy: ADMIN,
      },
      {
        id: "po-05",
        creatorId: "koc-lam",
        bookingId: "bk-10",
        kind: "fee",
        amount: 4_000_000,
        paidAt: "2026-09-15",
        reference: "CK 150926 LAMHAN",
        recordedBy: ADMIN,
      },
    ],
    activity: [
      { creatorId: "koc-ansan", at: "2026-08-20T03:00:00Z", actor: ADMIN, text: "Thêm vào danh sách KOC" },
      {
        creatorId: "koc-ansan",
        at: "2026-09-01T03:00:00Z",
        actor: ADMIN,
        text: "Ký hợp đồng HĐ-KOC-2609-01",
      },
      {
        creatorId: "koc-ansan",
        at: "2026-09-19T12:05:00Z",
        actor: ADMIN,
        text: "Ghi bài đã đăng: Quà Tết sớm cho bố mẹ ở quê",
      },
      {
        creatorId: "koc-ansan",
        at: "2026-09-30T03:00:00Z",
        actor: ADMIN,
        text: "Gửi hàng mẫu Ghế massage DV-S7",
      },
      {
        creatorId: "kol-mehien",
        at: "2026-09-12T12:00:00Z",
        actor: OWNER,
        text: "Ghi bài đã đăng: Review máy lọc nước ion kiềm",
      },
      { creatorId: "kol-seoul", at: "2026-09-25T03:00:00Z", actor: OWNER, text: "Thêm vào danh sách KOL" },
      {
        creatorId: "koc-lam",
        at: "2026-09-18T03:00:00Z",
        actor: ADMIN,
        text: "Tạm dừng hợp tác: đăng trễ hai lần",
      },
    ],
  };
}
